Models/_MyContentViewModel.cs
namespace ComnuyWebWithAPI.Models
{
    public class _ContentDeliveryModel
    {
        public List<Tool> Tools { get; set; }
        public Tool Tool { get; set; }
        public List<Tool> RandomTools { get; set; }
        public List<Tool> ToolsOrderByDate { get; set; }
        public List<ToolGroup> ToolGroups { get; set; }
        public ToolGroup ToolGroup { get; set; }
        public int SelectedToolGroupId { get; set; }
    }
}

Controllers/ContentViewController.cs
using ComnuyWebWithAPI.Data;
using ComnuyWebWithAPI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace ComnuyWebWithAPI.Controllers
{
    public class ContentViewController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ContentViewController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index(int selectedType)
        {
            List<Tool> toolsFromDb;
            List<ToolGroup> toolGroupsFromDb;

            if (selectedType == 1)
            {
                toolsFromDb = _context.Tools.ToList();
            } else
            {
                toolsFromDb = _context.Tools.Where(x => x.ToolGroup == selectedType).ToList();
            }
            toolGroupsFromDb = _context.ToolGroups.ToList();

            var model = new _ContentDeliveryModel
            {
                Tools = toolsFromDb,
                ToolGroups = toolGroupsFromDb,
                SelectedToolGroupId = selectedType

            };
            return View(model);
        }

        public IActionResult ShowToolDetail(int toolId)
        {
            Tool toolFromDb;
            ToolGroup toolGroup;
            bool checkIfFavoriteExist;

            if (toolId != 0)
            {
                toolFromDb = _context.Tools.SingleOrDefault(x => x.Id == toolId);

                if (toolFromDb != null)
                {
                    checkIfFavoriteExist = _context.ToolFavoritesFromUsers.Any(x => x.ToolId == toolId && x.UserName == User.Identity.Name);
                    toolGroup = _context.ToolGroups.SingleOrDefault(x => x.Id == toolFromDb.ToolGroup);
                    var model = new _ContentDeliveryModel
                    {
                        Tool = toolFromDb,
                        ToolGroup = toolGroup,
                        IsFavoriteForUser = checkIfFavoriteExist
                    };
                    return View(model);
                } else
                {
                    return NotFound();
                }
            } 

            return View();
        }

        [Authorize]
        public IActionResult MyContent()
        {
            var toolsFromDb = _context.Tools.Where(x => x.Owner == User.Identity.Name).ToList();
            var toolGroupsFromDb = _context.ToolGroups.ToList();

            var model = new _ContentDeliveryModel
            {
                Tools = toolsFromDb,
                ToolGroups = toolGroupsFromDb

            };
            return View(model);
        }

        [Authorize]
        public IActionResult CreateOrEditTool(int id)
        {
            var toolGroups = _context.ToolGroups.ToList();

            if (id != 0)
            {
                var toolPostingFromDb = _context.Tools.SingleOrDefault(x => x.Id == id);

                if (toolPostingFromDb.Owner != User.Identity.Name)
                {
                    return Unauthorized();
                }

                if (toolPostingFromDb != null)
                {
                    ViewBag.ToolGroups = toolGroups;
                    return View(toolPostingFromDb);
                }
                else
                {
                    return NotFound();
                }
            }

            ViewBag.ToolGroups = toolGroups;
            return View();
        }

        [Authorize]
        public IActionResult SubmitCreateOrEditTool(Tool tool, IFormFile file)
        {
            var toolId = tool.Id;
            string uploadsFolder;
            string toolFolder;
            string fileExtension;
            string uniqueFileName;
            string filePath;

            tool.LastChangesDate = DateTime.UtcNow;
            tool.LastChangeUser = User.Identity.Name;

            if (toolId == 0)
            {
                if (file != null)
                {

                    int nextDbId;
                    if (_context.Tools.Any())
                    {
                        nextDbId = _context.Tools.Max(t => t.Id) + 1;
                    }
                    else
                    {
                        nextDbId = 1;
                    }
                    string nextDbIdString = nextDbId.ToString();

                    string toolFolderString = nextDbIdString;

                    uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "Pictures\\Tool\\");
                    toolFolder = Path.Combine(uploadsFolder, toolFolderString);
                    Directory.CreateDirectory(toolFolder);

                    fileExtension = Path.GetExtension(file.FileName);

                    uniqueFileName = $"{tool.Name}_{nextDbIdString}{fileExtension}";
                    filePath = Path.Combine(toolFolder, uniqueFileName);


                    using (var fileStream = file.OpenReadStream())
                    {
                        using (Image image = Image.Load(fileStream))
                        {
                            // Hier wird das Bild auf die Zielgröße skaliert (kann je nach Bedarf angepasst werden)
                            int targetWidth = 250;
                            int targetHeight = 225;
                            image.Mutate(x => x.Resize(new ResizeOptions
                            {
                                Mode = ResizeMode.BoxPad,
                                Size = new Size(targetWidth, targetHeight)
                            }));

                            // Speichern des komprimierten Bildes als PNG
                            using (var pngFileStream = new FileStream(filePath, FileMode.Create))
                            {
                                image.SaveAsPng(pngFileStream);
                            }
                        }
                    }

                    tool.Picture_1 = Path.Combine("\\Pictures\\Tool\\", toolFolderString, uniqueFileName);
                }
                else if (file == null)
                {
                    tool.Picture_1 = Path.Combine("\\Pictures\\Tool\\Placeholder\\placeholder.png");
                }

                tool.Owner = User.Identity.Name;
                _context.Tools.Add(tool);

            } else if (toolId != 0) 
            {
                var toolFromDb = _context.Tools.FirstOrDefault(x => x.Id == tool.Id);
                string toolFromDbId = toolFromDb.Id.ToString();

                if (file != null && (toolFromDb.Picture_1 != tool.Picture_1))
                {
                    string deleteFilePath = Path.Combine(_webHostEnvironment.WebRootPath, toolFromDb.Picture_1);
                    FileInfo fileInfo = new FileInfo(deleteFilePath);
                    if (fileInfo.Exists)
                    {
                        fileInfo.Delete();
                    }
                    uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "Pictures\\Tool\\");
                    toolFolder = Path.Combine(uploadsFolder, toolFromDbId);
                    fileExtension = Path.GetExtension(file.FileName);
                    uniqueFileName = $"{tool.Name}_{toolFromDbId}{fileExtension}";
                    filePath = Path.Combine(toolFolder, uniqueFileName);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    toolFromDb.Picture_1 = Path.Combine("\\Pictures\\Tool\\", toolFromDbId, uniqueFileName);
                }

                toolFromDb.Name = tool.Name;
                toolFromDb.Description = tool.Description;
                toolFromDb.ShortDescription = tool.ShortDescription;
                toolFromDb.WebAddress = tool.WebAddress;
                toolFromDb.ToolGroup = tool.ToolGroup;
                toolFromDb.LastChangeUser = tool.LastChangeUser;
                toolFromDb.LastChangesDate = DateTime.UtcNow;


            }

            _context.SaveChanges();

            return RedirectToAction("MyContent");
        }

        [Authorize]
        [HttpPost]
        public IActionResult DeleteToolFromDb(int id)
        {
            if (id != 0)
            {
                var toolPostingFromDb = _context.Tools.SingleOrDefault(x => x.Id == id);

                if (toolPostingFromDb.Owner != User.Identity.Name)
                {
                    return Unauthorized();
                } else if (toolPostingFromDb.Owner == null)
                {
                    return Unauthorized();
                }

                if (toolPostingFromDb != null)
                {

                    if ( toolPostingFromDb.Picture_1 != "\\Pictures\\Tool\\Placeholder\\placeholder.png")
                    {
                        string webRootPath = _webHostEnvironment.WebRootPath;
                        string absoluteImagePath = Path.Combine(webRootPath + "\\Pictures\\Tool\\" + toolPostingFromDb.Id);
                        if (Directory.Exists(absoluteImagePath))
                        {
                            Directory.Delete(absoluteImagePath, recursive: true);
                        }
                    }

                    _context.Tools.Remove(toolPostingFromDb);
                    _context.SaveChanges();
                } else
                {
                    return NotFound();
                }
            } else
            {
                return BadRequest();
            }

            return Ok();
        }

        [Authorize]
        public IActionResult FavoritesContentTools()
        {

Views/ContentView/CreateOrEditTool.cshtml
@model ComnuyWebWithAPI.Models.Tool 

<partial name="_HeaderSectionBackgroundPartial" />

<div class="container">
    <main role="main" class="my-5">
        <form asp-controller="ContentView" asp-action="SubmitCreateOrEditTool" enctype="multipart/form-data">

            <div class="card-header">
                <h5>Tool erstellen oder bearbeiten</h5>
            </div>

            <div class="card-body mt-3">

                <input hidden asp-for="Id" />

                @{
                    if (Model != null && Model.Id != 0 && Model.Picture_1 != null)
                    {
                        <div class="d-flex justify-content-start mb-5">
                            <img class="rounded d-block img border" width="200" height="200" src="@Model.Picture_1">
                        </div>
                    }

                }

                <div class="row mb-2">
                    <div class="col">
                        <input class="form-control" asp-for="Name" type="text" placeholder="Name des Tool" />
                    </div>
                    <div class="col">
                        <input id="shortDescriptionInput" class="form-control" asp-for="ShortDescription" type="text" maxlength="100" placeholder="Kurze Beschreibung" />
                        <small id="charCount" class="text-muted">
                            <span>0</span> / 100 Zeichen
                        </small>
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col">
                        <textarea rows="6" class="form-control" asp-for="Description" placeholder="Ausführliche Beschreibung"></textarea>
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col">
                        <input class="form-control" asp-for="WebAddress" type="url" placeholder="Webseite" />
                    </div>
                    <div class="col">
                        <select class="form-control form-select" asp-for="ToolGroup">
                            @foreach (var toolGroup in ViewBag.ToolGroups)
                            {
                                if (toolGroup.Id != 1)
                                {
                                    <option value="@toolGroup.Id">@toolGroup.Name</option>
                                }
                            }
                        </select>
                    </div>
                </div>

                @{
                    if (Model != null && Model.Id != 0 && Model.Picture_1 != null && Model.Picture_1 == "\\Pictures\\Tool\\Placeholder\\placeholder.png")
                    {
                        <div>
                            <p class="text-info">Durch das Auswählen eines neuen Bildes, wird der Platzhalter ersetzt!</p>
                        </div>
                    }
                    else if (Model != null && Model.Id != 0 && Model.Picture_1 != null)
                    {
                        <div>
                            <p class="text-danger">Durch das Auswählen eines neuen Bildes, wird das vorhandene ersetzt!</p>
                        </div>
                    }

                }

                <div class="input-group mb-3">
                    <label class="input-group-text" for="formFile">Bild</label>
                    <input type="file" class="form-control" id="formFile" name="file" @*multiple*@ accept="image/*" @*max="5"*@>
                </div>

                @*        <div id="imagePreview"></div>*@

                <div class="card-footer mt-4">
                    <button class="btn btn-primary" type="submit">Speichern</button>
                </div>

            </div>

        </form>
    </main>
</div>

<script>

    // Counter for shortDescription
    const inputElement = document.getElementById('shortDescriptionInput');
    const charCountElement = document.getElementById('charCount');

    inputElement.addEventListener('input', function () {
        const charCount = inputElement.value.length;
        charCountElement.querySelector('span').textContent = charCount;
    });

    //Preview image after select

    // Preview image loader
    //function showImagePreview(input) {
    //    var previewContainer = document.getElementById("imagePreview");
    //    previewContainer.innerHTML = "";

    //    if (input.files) {
    //        var filesAmount = input.files.length;
    //        for (i = 0; i < filesAmount; i++) {
    //            var reader = new FileReader();

    //            reader.onload = function (event) {
    //                var image = document.createElement("img");
    //                image.src = event.target.result;
    //                image.className = "preview-image";
    //                previewContainer.appendChild(image);
    //            }

    //            reader.readAsDataURL(input.files[i]);
    //        }
    //    }
    //}

    //document.getElementById("formFile").addEventListener("change", function () {
    //    showImagePreview(this);
    //});
</script>

Views/ContentView/FavoritesContentTools.cshtml
@model _ContentDeliveryModel

<partial name="_HeaderSectionBackgroundPartial" />

<div class="container">
    <main role="main" class="my-5">
        <div class="mb-5">
            <a class="btn btnGreen" asp-controller="ContentView" asp-action="CreateOrEditTool"><i class="fas fa-plus me-3"></i>Neues Tool</a>
        </div>


        <table id="myContentToolTable" class="stripe hover" style="width:100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Kurzbeschreibung</th>
                    <th>Plattform</th>
                    <th>Aktionen</th>
                </tr>
            </thead>

            <tbody>
                <partial name="_MyContentToolPartial" />
            </tbody>
        </table>
    </main>
</div>

@section scripts {
    <script>
        new DataTable('#myContentToolTable', {
            order: [[0, 'asc']],
            pagingType: 'full_numbers',
            scrollX: true,
            language: {
                url: 'https://cdn.datatables.net/plug-ins/1.11.5/i18n/de-DE.json'
            }
        });

        function deleteToolFromDb(id) {
            document.addEventListener('confirm.mdb.popconfirm', () => {
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("DeleteToolFromDb")",
                    data: { id: id },
                    success: function (msg) {
                        Swal.fire('Das Tool wurde gelöscht!', '', 'success').then((result) => {
                            if (result.isConfirmed) {
                                location.reload();
                            }
                        });
                    },
                    error: function (msg) {
                        Swal.fire('Ups, da ist etwas schief gelaufen!', '', 'error')
                    }
                });
            });
        }

        function showSuccessAlert() {
            mdb.Alert.getInstance(document.getElementById("alert-success-delete-tool-from-db")).show();
        }
    </script>
}

Views/ContentView/Index.cshtml
@model _ContentDeliveryModel

<partial name="_HeaderSectionBackgroundPartial" />

<div class="container">
    <main role="main" class="my-5">
        <div class="accordion mb-5" id="accordionExample">
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingOne">
                    <button class="accordion-button comnuyTextColorGrey"
                            type="button"
                            data-mdb-toggle="collapse"
                            data-mdb-target="#collapseOne"
                            aria-expanded="true"
                            aria-controls="collapseOne">
                        Filter
                    </button>
                </h2>
                <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-mdb-parent="#accordionExample">
                    <div class="accordion-body">
                        <div class="col-4">
                            <label for="toolTypeSelectDropDown">Kategorie:</label>
                            <select id="toolTypeSelectDropDown" class="form-control form-select" onchange="reloadIndexPage(this.value)">
                                @foreach (var toolGroup in Model.ToolGroups)
                                {
                                    @if (toolGroup.Id == Model.SelectedToolGroupId)
                                    {
                                        <option value="@toolGroup.Id" selected>@toolGroup.Name</option>
                                    }
                                    else
                                    {
                                        <option value="@toolGroup.Id">@toolGroup.Name</option>
                                    }
                                }
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <table id="contentToolTable" class="stripe hover" style="width:100%">
            <thead>
                <tr>
                    <th class="text-center">Bild</th>
                    <th class="text-center">Typ</th>
                    <th class="text-center">Name</th>
                    <th class="text-center">Kurzbeschreibung</th>
                </tr>
            </thead>
            <tbody>
                <partial name="_ContentToolPartial" />
            </tbody>
        </table>
    </main>
</div>

@section scripts {
    <script>
        new DataTable('#contentToolTable', {
            order: [[0, 'asc']],
            pagingType: 'full_numbers',
            scrollX: true,
            language: {
                url: 'https://cdn.datatables.net/plug-ins/1.11.5/i18n/de-DE.json'
            }
        });

        function reloadIndexPage(selectedType) {
            var url = '@Url.Action("Index")' + '?selectedType=' + selectedType;
            window.location.href = url;
        }

        function showToolDetail(toolId) {
            var url = '@Url.Action("ShowToolDetail")' + '?toolId=' + toolId;
            window.location.href = url;
        }
    </script>
}

Views/ContentView/MyContent.cshtml
@model _ContentDeliveryModel

<partial name="_HeaderSectionBackgroundPartial" />

<div class="container">
    <main role="main" class="my-5">
        <div class="mb-5">
            <a class="btn btnGreen" asp-controller="ContentView" asp-action="CreateOrEditTool"><i class="fas fa-plus me-3"></i>Neues Tool</a>
        </div>


        <table id="myContentToolTable" class="stripe hover" style="width:100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Kurzbeschreibung</th>
                    <th>Plattform</th>
                    <th>Aktionen</th>
                </tr>
            </thead>

            <tbody>
                <partial name="_MyContentToolPartial" />
            </tbody>
        </table>
    </main>
</div>

@section scripts {
    <script>
        new DataTable('#myContentToolTable', {
            order: [[0, 'asc']],
            pagingType: 'full_numbers',
            scrollX: true,
            language: {
                url: 'https://cdn.datatables.net/plug-ins/1.11.5/i18n/de-DE.json'
            }
        });

        function deleteToolFromDb(id) {
            document.addEventListener('confirm.mdb.popconfirm', () => {
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("DeleteToolFromDb")",
                    data: { id: id },
                    success: function (msg) {
                        Swal.fire('Das Tool wurde gelöscht!', '', 'success').then((result) => {
                            if (result.isConfirmed) {
                                location.reload();
                            }
                        });
                    },
                    error: function (msg) {
                        Swal.fire('Ups, da ist etwas schief gelaufen!', '', 'error')
                    }
                });
            });
        }

        function showSuccessAlert() {
            mdb.Alert.getInstance(document.getElementById("alert-success-delete-tool-from-db")).show();
        }
    </script>
}

Views/ContentView/ShowToolDetail.cshtml
@model _ContentDeliveryModel
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<partial name="_HeaderSectionBackgroundPartial" />

<div class="container">
    <main role="main" class="my-5">
        <section class="mb-10">
            <div class="row">
                <div class="col-lg-6 col-xl-7 pe-lg-4 mb-5 mb-lg-0">
                    <h2 class="fw-bold mb-3">@Model.Tool.Name</h2>
                    <p class="mb-4">Kategorie: <span><strong>@Model.ToolGroup.Name</strong></span></p>
                    <div class="border rounded-5 p-4 mb-4" style="max-width: 500px;">
                        <h6 class="comnuyTextColorGreen"><strong>Kurzbeschreibung</strong></h6>
                        <p>@Model.Tool.ShortDescription</p>
                        <h6 class="comnuyTextColorGreen"><strong>Beschreibung</strong></h6>
                        <p>@Model.Tool.Description</p>
                    </div>
                    <p class="mb-4">Erstellt von: <span><strong>@Model.Tool.Owner</strong></span></p>
                    <p class="mb-4">Letzte Änderung am: <span><strong>@Model.Tool.LastChangesDate.Date.ToShortDateString()</strong></span></p>
                    <p class="mb-4">Letzte Änderung von: <span><strong>@Model.Tool.LastChangeUser</strong></span></p>
                    <div class="mt-4 pt-2" style="max-width: 500px;">
                        <div class="mt-3">
                            <div class="mb-5">
                                @if (Model.Tool.WebAddress != null)
                                {
                                    <a href="@Model.Tool.WebAddress" class="btn btnGreen"><i class="fas fa-location-arrow me-3"></i>Zur Quelle</a>
                                }
                                @if (SignInManager.IsSignedIn(User))
                                {
                                    if (Model.IsFavoriteForUser)
                                    {
                                        <a class="btn btnDanger" asp-controller="ContentView" asp-action="CheckAndSetFavoriteTool" asp-route-toolId="@Model.Tool.Id"><i class="fas fa-toolbox me-3"></i>Aus dem Werkzeugkasten entfernen</a>
                                    } else
                                    {
                                        <a class="btn btnGreen" asp-controller="ContentView" asp-action="CheckAndSetFavoriteTool" asp-route-toolId="@Model.Tool.Id"><i class="fas fa-toolbox me-3"></i>In den Werkzeugkasten legen</a>
                                    }
                                }
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-xl-5 ps-lg-4">
                    <div class="bg-image hover-overlay ripple d-flex justify-content-center" data-mdb-ripple-color="light">
                        <img class="img-fluid toolPicture" src="@Model.Tool.Picture_1" alt="Image placeholder">
                    </div>
                </div>
            </div>
        </section>
    </main>
</div>

Views/ContentView/_ContentToolPartial.cshtml
@model _ContentDeliveryModel

    @{
        foreach (Tool tool in Model.Tools)
        {
            <tr role="button" onclick="showToolDetail(@tool.Id)">
                <td>
                    <div style="display: flex; justify-content: center; align-items: center;">
                        <img class="rounded d-block img" width="100" height="80" src="@tool.Picture_1">
                    </div>
                </td>
                <td class="align-middle">
                    @{
                        var toolGroup = Model.ToolGroups.FirstOrDefault(tg => tg.Id == tool.ToolGroup);
                        if (toolGroup != null)
                        {
                            @toolGroup.Name
                        }
                    }
                </td>
                <td class="align-middle">
                    <div>
                        <span style="display: block;">@tool.Name</span>
                    </div>
                </td>
                <td class="align-middle">
                    <div>
                        <span style="display: block;">@tool.ShortDescription</span>
                    </div>
                </td>
            </tr>
        }
    }

Views/ContentView/_MyContentToolPartial.cshtml
@model _ContentDeliveryModel

        @{
            foreach(Tool tool in Model.Tools)
            {
                <tr>
                    <td>@tool.Name</td>
                    <td>@tool.ShortDescription</td>
                    <td>
                        @{
                            // Den Namen der Toolgruppe anhand der ID abrufen
                            var toolGroup = Model.ToolGroups.FirstOrDefault(tg => tg.Id == tool.ToolGroup);
                            if (toolGroup != null)
                            {
                                @toolGroup.Name
                            }
                        }
                    </td>
                    <td style="width: 150px">
                        <a class="btn btnGreen" asp-route-id="@tool.Id" asp-controller="ContentView" asp-action="CreateOrEditTool"><i class="fas fa-pencil"></i></a>
                <button type="button" class="btn btnDanger popconfirm-toggle" onclick="deleteToolFromDb(@tool.Id)" data-mdb-message="Möchtest du das Tool @tool.Name wirklich löschen?" data-mdb-id="@tool.Id"><i class="far fa-trash-can"></i></button>
                    </td>
                </tr>
            }
        }